StudentApplicationECommerce/Models/ErrorViewModel.cs
namespace StudentWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudentApplicationECommerce/Models/Students.cs
namespace StudentWebApp.Models
{
    public class Students
    {
        public int studId { get; set; }
        public string Name { get; set; }

        public string email { get; set; }

        public string MobNo { get; set; }

        public string address { get; set; }
        public DateTime AdmissionDate { get; set; }
        public double fees { get; set; }

        public string status { get; set; }

    }
}

StudentApplicationECommerce/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StudentWebApp.Models;
using System.Diagnostics;

namespace StudentWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentApplicationECommerce/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using StudentWebApp.Models;
using StudentWebApp.Services;

namespace StudentWebApp.Controllers
{
    public class StudentsController : Controller
    {
        private IStudentService _studentService;
        public StudentsController(IStudentService studentService) {
            _studentService = studentService;
        }

        public IActionResult Index()
        {
           
            return View();
        }

        [HttpGet]
        public IActionResult GetResult()
        {
            var p = _studentService.GetStudents();
            return View(p);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(Students students)
        {
            var p = _studentService.insert(students);

            return View(p);
        }
       

        
        public IActionResult Delete(int id)
        {
            var p = _studentService.delete(id);
            return RedirectToAction("GetResult");
        }
        [HttpGet]
        public IActionResult Update()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Update(Students model)
        {
            _studentService.update(model);
            return RedirectToAction("GetResult");
        }
        
    }
}

StudentApplicationECommerce/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StudentApplicationECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="GetResult">Show Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - StudentWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StudentApplicationECommerce/Views/Students/GetResult.cshtml
@model IEnumerable<StudentWebApp.Models.Students>;

 <h3>Show All Students</h3>
<div>
    <table class="table">
        <thead>
            <tr>
                <th>Student Id</th>
                <th>Student Name</th>
                <th>Student Email</th>
                <th>Student Address</th>
                <th>Student Mobile_No</th>
                <th>Student Admission Date</th>
                <th>Student Fees</th>
                <th>Student Status</th>
                <th>Action</th>
            </tr>

        </thead>
        <tbody>
            @foreach (var Student in Model)
            {
                <tr>
                    <td>@Student.studId</td>
                    <td>@Student.Name</td>
                    <td>@Student.email</td>
                    <td>@Student.address</td>
                    <td>@Student.MobNo</td>
                    <td>@Student.AdmissionDate</td>
                    <td>@Student.fees</td>
                    <td>@Student.status</td>
                    <td>
                        <a href="/Students/Delete?id=@Student.studId"  class="btn btn-danger">Delete</a>
                     </td>
                    <td>
                        <a href="/Students/Update" class="btn btn-warning">Update</a>
                    </td>

    



                </tr>
               
            }
           
           



        </tbody>
    </table>
</div>

StudentApplicationECommerce/Views/Students/Register.cshtml

<h1>Register Student Form</h1>
<hr />
<div>
    <form action="/Students/Register" method="post">
        <table>
            <tr>
                <td>Student Name</td>
                <td><input type="text" name="Name" id="Name" /></td>
            </tr>
            <tr>
                <td>Student Email</td>
                <td> <input type="text" name="email" id="email" /></td>
            </tr>
            <tr>
                <td>Student Mobile No</td>
                <td> <input type="text" name="MobNo" id="MobNo" /></td>
            </tr>
            <tr>
                <td>Student Address</td>
                <td> <input type="text" name="address" id="address" /></td>
            </tr>
            <tr>
                <td>Student fee</td>
                <td> <input type="text" name="fees" id="fees" /></td>
            </tr>




        </table>
        <button type="submit" name="submit" id=" submit" class="btn btn-success">Submit</button>
    </form>
</div>

StudentApplicationECommerce/Views/Students/Update.cshtml

<h1>Update Student Form</h1>
<hr />
<div>
    <form action="/Students/Update" method="post">
        <table>
            <tr>
                <td>Student id</td>
                <td><input type="number" name="studid" id="id" /></td>
            </tr>
            <tr>
                <td>Student Name</td>
                <td><input type="text" name="Name" id="Name" /></td>
            </tr>
            <tr>
                <td>Student Email</td>
                <td> <input type="text" name="email" id="email" /></td>
            </tr>
            <tr>
                <td>Student Mobile No</td>
                <td> <input type="text" name="MobNo" id="MobNo" /></td>
            </tr>
            <tr>
                <td>Student Address</td>
                <td> <input type="text" name="address" id="address" /></td>
            </tr>
           
            <tr>
                <td>Student status</td>
                <td><input type="text" name="status" id="status" /></td>
            </tr>




        </table>
        <button type="submit" name="submit" id=" submit" class="btn btn-success">Submit</button>
    </form>
</div>